spin_manifest_version = 2

[application]
authors = ["Truls Aagaard <truls@aagaard.io>"]
description = "echo"
name = "echo"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "echo"

[component.echo]
source = "target/echo.wasm"
exclude_files = ["**/node_modules"]
[component.echo.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]